repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: ./web/node_modules/.bin/eslint
        language: system
        files: ^web/src/.*\.(js|jsx)$
        args:
          - --config
          - web/eslint.config.js
        pass_filenames: true

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.0
    hooks:
      - id: gitleaks
